-- Sync learnset auto (feh_gen_sql.py) : héros IntID 1415-1418, généré le 2026-09-19.
-- Compétences neuves absentes de feh.skills (10, vérifiées par wiki_name exact).
-- À coller dans Supabase Studio (SQL Editor), APRÈS le(s) fichier(s) add_hero(es) correspondant(s).
begin;

-- 1) Compétences
insert into feh.skills
  (wiki_name,name,group_name,tag_id,scategory,use_range,refine_path,description,required,next,exclusive,sp,can_use_move,can_use_weapon,might,stat_modifiers,cooldown,weapon_effectiveness,properties) values
  ('Bold Stance','Bold Stance','Bold Stance','SID_攻防一体の陣','passiveb',null,null,'For foes within 3 rows or 3 columns centered on unit, inflicts Atk/Spd/Def/Res-5, neutralizes foe''s bonuses, and increases the Spd difference necessary for foe to make a follow-up attack by 10 during combat.<br><br>If unit is within 3 spaces of an ally or if there is a support partner with Support Rank of S+ on the map, inflicts Atk/Spd/Def-5 on foe, unit deals damage = 20% of unit''s Spd (excluding area-of-effect Specials), reduces damage from foe''s attacks by 20% of unit''s Spd (excluding area-of-effect Specials), and grants Special cooldown count-2 to unit before foe''s first attack during combat, and also, if unit''s Special is ready or triggered before or during this combat, reduces damage from foe''s attacks to a maximum of 1 during combat (once per combat; excluding area-of-effect Specials).',null,null,true,400,'Infantry,  Armored,  Cavalry,  Flying',null,null,'0,0,0,0,0',null,null,'random_owner'),
  ('Bow of Sacae','Bow of Sacae','Bow of Sacae','SID_サカの娘二人の弓','weapon',2,null,'Enables【Canto (２)】. Accelerates Special trigger (cooldown count-1). Effective against flying foes.<br><br>For unit and allies within 3 rows or 3 columns centered on unit, grants Atk/Spd/Def/Res+X (for unit, X = 15; for allies, X = 5), deals +Y damage (excluding area-of-effect Specials; for unit, Y = 25; for allies, Y = 10), and grants Special cooldown count-2 before unit''s or ally''s first follow-up attack during combat.<br><br>Reduces damage from foe''s attacks by 15 (excluding area-of-effect Specials) and neutralizes effects that inflict "Special cooldown charge -X" on unit during combat, and restores 7 HP to unit after combat.<br><br>Unit can use the following【Style】:<br>――――――― Astra Storm Style ――――――――<br>Unit can attack foes within 6 spaces of unit and 3 rows or 3 columns centered on unit regardless of unit''s range.<br><br>Unit suffers a counterattack if any of the following conditions are met: foe is armored with Range = 2, foe can counterattack regardless of unit''s range, or foe''s Range is the same as the distance between unit and foe.<br><br>Unit cannot move or attack structures, after-combat movement effects do not occur, unit''s area-of-effect Specials cannot be triggered, and remaining movement granted from Canto is treated as 0. Skill effect''s Range is treated as 2. This Style can be used only once per turn.<br>―――――――――――――――――――――――――<br><br>【Canto (２)】<br>After an attack, Assist skill, or structure destruction, unit can move ２ space(s). (Once per turn. Only highest value applied. Does not stack.)<br><br>【Style】<br>Change Style using the Style button at the bottom of the screen.<br><br>A unit''s Style is only active when that unit is taking an action. Style use is disabled when unit is deployed using Pair Up or when unit is equipped with multiple skills that have a Style.','Silver Bow',null,true,400,'Infantry,  Armored,  Cavalry,  Flying','Red Bow,  Blue Bow,  Green Bow,  Colorless Bow',14,'0,14,0,0,0',-1,'flying',null),
  ('Certain Blow','Certain Blow','Certain Blow','SID_凶鳥の一撃','passivea',null,null,'Enables【Canto (２)】.<br><br>At start of turn, and after unit acts (if Canto triggers, after Canto), inflicts Atk/Spd/Def-7 on closest foes and foes within 2 spaces of those foes through their next actions.<br><br>If unit initiates combat or if【Bonus】is active on unit, grants Atk/Spd/Def+10 to unit, unit deals +X damage (excluding area-of-effect Specials; X = 60% of the highest value of total penalties among target and foes within 2 spaces of target), and reduces damage from foe''s first attack by 7 during combat ("first attack" normally means only the first strike; for effects that grant "unit attacks twice," it means the first and second strikes).<br><br>【Canto (２)】<br>After an attack, Assist skill, or structure destruction, unit can move ２ space(s). (Once per turn. Only highest value applied. Does not stack.)<br><br>【Bonus】<br>All effects that last "for 1 turn" or "that turn only." Includes bonuses granted by a skill like Rally or Hone and positive status effects (extra movement or effects like Dominance).','Death Blow 3;Darting Blow 3',null,false,300,'Infantry,  Armored,  Cavalry,  Flying','Red Sword,  Blue Lance,  Green Axe,  Red Bow,  Blue Bow,  Green Bow,  Colorless Bow,  Red Dagger,  Blue Dagger,  Green Dagger,  Colorless Dagger,  Red Beast,  Blue Beast,  Green Beast,  Colorless Beast',null,'0,0,0,0,0',null,null,'random_owner'),
  ('Dull Suppress','Dull Suppress','Dull Suppress','SID_牽制射撃・強化無効','passiveb',null,null,'Inflicts Atk/Spd/Def-5 on foes within 3 rows or 3 columns centered on unit during combat.<br><br>Inflicts Atk/Spd/Def-4 on foe, neutralizes foe''s bonuses, unit deals +15 damage (excluding area-of-effect Specials), and reduces damage from foe''s attacks by 15 during combat (excluding area-of-effect Specials).','Seal SpdDef 2',null,false,400,'Infantry,  Armored,  Cavalry,  Flying','Red Bow,  Blue Bow,  Green Bow,  Colorless Bow',null,'0,0,0,0,0',null,null,'random_owner'),
  ('Hunters Volley','Hunter''s Volley','Hunter''s Volley','SID_ハンターボレー','special',null,null,'When Special triggers, boosts damage by 70% of unit''s Atk.<br><br>Reduces damage from foe''s first attack by 40% during combat ("first attack" normally means only the first strike; for effects that grant "unit attacks twice," it means the first and second strikes).<br><br>If it is unit''s first combat initiated by unit this turn, and if the distance from unit''s space to foe''s space ≤ 2, unit attacks twice during combat, but if unit can make a follow-up attack, calculates damage from unit''s attacks at 80%. (This calculation stacks with other effects that calculate damage at X% such as Potent Follow.)','Dragon Fang',null,false,500,'Infantry,  Armored','Red Bow,  Blue Bow,  Green Bow,  Colorless Bow',null,null,5,null,'offensive_special,random_owner'),
  ('Ornate Bow','Ornate Bow','Ornate Bow','SID_草原の飾り弓','weapon',2,null,'Enables【Canto (Dist.; Max ３, Min １)】. Accelerates Special trigger (cooldown count-1). Effective against beast, cavalry, and flying foes.<br><br>If foe in combat is a beast, cavalry, or flying foe, foes'' Savior effects will not trigger.<br><br>At start of player phase or enemy phase, grants Atk/Spd+6,【Truly Incited】, and "reduces the percentage of foe''s non-Special ''reduce damage by X%'' skills by 50% during combat (excluding area-of-effect Specials)" to unit and allies within 2 spaces of unit for 1 turn.<br><br>Grants Atk/Spd/Def/Res+15 to unit, unit deals +25 damage (excluding area-of-effect Specials), and reduces damage from foe''s attacks by 15 during combat (excluding area-of-effect Specials), and also, if foe is beast, cavalry, or flying, or if decreasing the Spd difference necessary to make a follow-up attack by 10 would allow unit to trigger a follow-up attack (excluding guaranteed or prevented follow-ups), triggers 【Potent Follow 100%】during combat.<br><br>【Canto (Dist.; Max ３, Min １)】<br>After an attack, Assist skill, or structure destruction, unit can move spaces = number of spaces from start position to end position unit moved prior to taking action (max ３; min １; if unit used a movement skill that warped them, unit can move １ space(s).)<br><br>【Truly Incited】<br>Grants bonus to Atk/Spd/Def/Res during combat = number of spaces from start position to end position of whoever initiated combat × 2 (max 8).<br><br>【Potent Follow 100%】<br>Triggers an additional follow-up attack immediately after unit''s standard follow-up attack and deals damage = 100% of unit''s normal attack damage (if unit cannot make a follow-up attack, this effect triggers when the standard follow-up attack would occur; this effect is treated like a follow-up attack, so effects like "reduce damage by X%" still apply, but this effect is not affected by effects that prevent follow-ups or "attacks twice" effects; only highest value applied; does not stack).','Silver Bow',null,true,400,'Infantry,  Armored,  Cavalry,  Flying','Red Bow,  Blue Bow,  Green Bow,  Colorless Bow',14,'0,14,0,0,0',-1,'beast,cavalry,flying',null),
  ('Quicken Null','Quicken Null','Quicken Null','SID_始鼓動・見切り','passivec',null,null,'At start of turn, at start of enemy phase (except for in Summoner Duels), and after combat, if Special cooldown count is at its maximum value, grants Special cooldown count-1 to unit.<br><br>Grants bonus to unit''s Atk/Spd/Def/Res = unit''s maximum Special cooldown count value + 2, unit deals +5 damage (excluding area-of-effect Specials), and reduces damage from foe''s first attack by 5 during combat ("first attack" normally means only the first strike; for effects that grant "unit attacks twice," it means the first and second strikes), and also, if unit''s Spd > foe''s Spd, neutralizes effects that guarantee foe''s follow-up attacks and effects that prevent unit''s follow-up attacks during combat.','Times Pulse 3',null,false,300,'Infantry',null,null,'0,0,0,0,0',null,null,'random_owner'),
  ('Sacaen Edicts','Sacaen Edicts','Sacaen Edicts','SID_正真サカの掟','passivea',null,null,'At start of player phase or enemy phase, grants【Laws of Sacae】and【Null Follow-Up】 to unit and allies within 2 spaces of unit for 1 turn.<br><br>Grants Atk/Spd/Def/Res+10 to unit, unit deals +7 damage (excluding area-of-effect Specials), reduces damage from foe''s attacks by 7 (excluding area-of-effect Specials), and disables skills of all foes excluding foe in combat during combat, and also, if decreasing the Spd difference necessary to make a follow-up attack by 10 would allow unit to trigger a follow-up attack (excluding guaranteed or prevented follow-ups), triggers 【Potent Follow 100%】during combat.<br><br>If unit is within 3 spaces of an ally with the 【Laws of Sacae】effect active, and unit''s HP > 1 and foe would reduce unit''s HP to 0, unit survives with 1 HP (once per combat; does not stack with non-Special effects that allow unit to survive with 1 HP if foe''s attack would reduce HP to 0).<br><br>【Laws of Sacae】<br>Grants Atk/Spd/Def/Res+X × 2 to unit, unit deals +X × 3 damage (excluding area-of-effect Specials), and reduces damage from foe''s attacks by X × 3 (excluding area-of-effect Specials) during combat (X = number of allies on the map with the Laws of Sacae effect active, including unit; max 3).<br><br>If unit initiates combat, inflicts【Share Spoils+】 on target and foes within 2 spaces of target through their next actions after combat.<br><br>【Null Follow-Up】<br>If unit''s Spd > foe''s Spd, neutralizes effects that guarantee foe''s follow-up attacks and effects that prevent unit''s follow-up attacks during combat.<br><br>【Potent Follow 100%】<br>Triggers an additional follow-up attack immediately after unit''s standard follow-up attack and deals damage = 100% of unit''s normal attack damage (if unit cannot make a follow-up attack, this effect triggers when the standard follow-up attack would occur; this effect is treated like a follow-up attack, so effects like "reduce damage by X%" still apply, but this effect is not affected by effects that prevent follow-ups or "attacks twice" effects; only highest value applied; does not stack).<br><br>【Share Spoils+】<br>Inflicts Atk/Spd/Def/Res-5 on unit during combat and neutralizes "reduces damage by X%" effects from unit''s non-Special skills (excluding area-of-effect Specials).<br><br>Once per turn for the entire map, if foe initiates combat and if unit is defeated in combat, grants another action to that foe after combat (this effect has priority over other similar effects aside from Share Spoils; if this status and Share Spoils are both active at the same time, they are both treated as having been triggered; other similar effects aside from Share Spoils are treated as not having triggered).',null,null,true,300,'Infantry,  Armored,  Cavalry,  Flying',null,null,'0,0,0,0,0',null,null,'random_owner'),
  ('Sacaen Hunter','Sacaen Hunter','Sacaen Hunter','SID_草原の狩人の弓','weapon',2,null,'Accelerates Special trigger (cooldown count-1). Effective against flying foes.<br><br>At start of turn, and after unit acts (if Canto triggers, after Canto), inflicts Spd/Def-7, 【Exposure】, and【Sabotage】on closest foes and foes within 2 spaces of those foes through their next actions.<br><br>If unit or ally on the map initiates combat and defeats a foe with the【Exposure】 effect active during combat, grants Atk/Spd【Great Talent】+4 to unit and allies on the map after combat.<br><br>Grants Atk/Spd/Def/Res+15 to unit, unit deals +25 damage (excluding area-of-effect Specials), reduces damage from foe''s attacks by 15 (excluding area-of-effect Specials), and disables skills of all foes excluding foe in combat during combat.<br><br>(This skill grants max of【Great Talent】+24 for unit and【Great Talent】+12 for allies.)<br><br>【Exposure】<br>Foe''s attacks deal +10 damage.<br><br>【Sabotage】<br>Inflicts penalty on unit''s Atk/Spd/Def/Res during combat = highest penalty on each stat between unit and allies within 2 spaces of unit. Calculates each stat penalty independently.<br><br>【Great Talent】<br>Adds value of Great Talent (+X) to specified stats (until end of battle; max value of X is determined by the stat reaching the limit of 99, each stat calculated separately and cannot exceed max value for each skill; stat increases are not treated as Bonus effects).','Silver Bow',null,true,400,'Infantry,  Armored,  Cavalry,  Flying','Red Bow,  Blue Bow,  Green Bow,  Colorless Bow',14,'0,14,0,0,0',-1,'flying',null),
  ('Zephyr Bow','Zephyr Bow','Zephyr Bow','SID_草原の風呼びの弓','weapon',2,null,'Accelerates Special trigger (cooldown count-1). Effective against flying foes. Unit can counterattack regardless of foe''s range.<br><br>Unit can move through foes'' spaces.<br><br>Unit can move to a space within 4 spaces of unit (treated as Warp movement).<br><br>At start of player phase or enemy phase, grants 【Empathy】,【Reflex】,and "increases Spd difference necessary for foe to make a follow-up attack by 10 during combat" to unit and allies within 2 spaces of unit for 1 turn.<br><br>Grants Atk/Spd/Def/Res+15 to unit, unit deals +25 damage (excluding area-of-effect Specials), and reduces damage from foe''s attacks by 15 during combat (excluding area-of-effect Specials), and also, if decreasing the Spd difference necessary to make a follow-up attack by 10 would allow unit to trigger a follow-up attack (excluding guaranteed or prevented follow-ups), triggers 【Potent Follow 100%】during combat.<br><br>【Empathy】<br>Grants bonus to unit''s Atk/Spd/Def/Res = number of types of Bonus effects, excluding stat bonuses, and Penalty effects, excluding stat penalties, active on player team and enemy team during combat (max 7).<br><br>【Reflex】<br>Reduces damage from foe''s first attack by 7 during combat ("first attack" normally means only the first strike; for effects that grant "unit attacks twice," it means the first and second strikes) and unit''s next attack deals damage = total damage reduced from foe''s first attack (by any source, including other skills; resets at end of combat). (For 1 turn.)<br><br>【Potent Follow 100%】<br>Triggers an additional follow-up attack immediately after unit''s standard follow-up attack and deals damage = 100% of unit''s normal attack damage (if unit cannot make a follow-up attack, this effect triggers when the standard follow-up attack would occur; this effect is treated like a follow-up attack, so effects like "reduce damage by X%" still apply, but this effect is not affected by effects that prevent follow-ups or "attacks twice" effects; only highest value applied; does not stack).','Silver Bow',null,true,400,'Infantry,  Armored,  Cavalry,  Flying','Red Bow,  Blue Bow,  Green Bow,  Colorless Bow',14,'0,14,0,0,0',-1,'flying',null)
on conflict (wiki_name) do nothing;

-- 2) Learnset lié (hero_id direct)
insert into feh.hero_learnset (hero_id, unit_wiki_name, skill_name, unlock_rarity) values
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Iron Bow',1),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Seal Spd 1',2),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Shadow Shift 1',2),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Steel Bow',2),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Night Sky',3),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Seal SpdDef 1',3),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Shadow Shift 2',3),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Silver Bow',3),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Astra',4),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Seal SpdDef 2',4),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Shadow Shift 3',4),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Bow of Sacae',5),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Dull Suppress',5),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Sacaen Edicts',5),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Shadow Shift X',5),
  ('lyn-earth-and-sky-1415','Lyn Earth and Sky','Wind Edge',5),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Iron Bow',1),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Death Blow 1',2),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Steel Bow',2),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Times Pulse 1',2),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Death Blow 2',3),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Glowing Ember',3),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Silver Bow',3),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Times Pulse 2',3),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Death Blow 3',4),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Ignis',4),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Times Pulse 3',4),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Bold Stance',5),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Certain Blow',5),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Quicken Null',5),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Waning Shot',5),
  ('takumi-divine-bow-prince-1416','Takumi Divine Bow Prince','Zephyr Bow',5),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','Death Blow 1',1),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','Iron Bow',1),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','AtkSpd Gap 1',2),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','Death Blow 2',2),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','Steel Bow',2),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','AtkSpd Gap 2',3),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','Harsh Command',3),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','Silver Bow',3),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','AtkSpd Gap 3',4),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','Death Blow 3',4),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','AtkSpd Liberate',5),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','Harsh Command Plus',5),
  ('rebecca-in-the-sun-s-rays-1417','Rebecca In the Suns Rays','Ornate Bow',5),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','Iron Bow',1),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','AR-O AtkSpd 1',2),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','Speedtaker 1',2),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','Steel Bow',2),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','AR-O AtkSpd 2',3),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','Dragon Gaze',3),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','Silver Bow',3),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','Speedtaker 2',3),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','AR-O AtkSpd 3',4),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','Dragon Fang',4),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','Speedtaker 3',4),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','AS Foresight Nix',5),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','AS Taker Burst',5),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','Hunters Volley',5),
  ('shamir-sniper-s-path-1418','Shamir Snipers Path','Sacaen Hunter',5);

commit;
