-- Sync learnset auto (feh_gen_sql.py) : héros IntID 1410, généré le 2026-09-03.
-- Compétences neuves absentes de feh.skills (4, vérifiées par wiki_name exact).
-- À coller dans Supabase Studio (SQL Editor), APRÈS le(s) fichier(s) add_hero(es) correspondant(s).
begin;

-- 1) Compétences
insert into feh.skills
  (wiki_name,name,group_name,tag_id,scategory,use_range,refine_path,description,required,next,exclusive,sp,can_use_move,can_use_weapon,might,stat_modifiers,cooldown,weapon_effectiveness,properties) values
  ('Distant Breath','Distant Breath','Distant Breath','SID_長距離ブレス','passiveb',null,null,'Inflicts Atk/Def/Res-4 on foe, unit deals damage = 20% of the greater of unit''s Def or Res (excluding area-of-effect Specials), reduces damage by 20% of the greater of unit''s Def or Res (excluding area-of-effect Specials), and unit makes a guaranteed follow-up attack, during combat.<br><br>Unit can use the following【Style】when there are no other allies on the player''s team with the same【Style】:<br>――――― Distant Breath Style ―――――<br>Unit can attack foes within 5 spaces of unit and 3 rows or 3 columns centered on unit regardless of unit''s range.<br><br>Unit suffers a counterattack if any of the following conditions are met: foe is armored, foe can counterattack regardless of unit''s range, or foe''s Range is the same as the distance between unit and foe.<br><br>Unit cannot move or attack structures, after-combat movement effects do not occur, unit''s area-of-effect Specials cannot be triggered, and remaining movement granted from Canto is treated as 0. Skill effect''s Range is treated as 1. Once used, this Style cannot be used for two turns.<br>――――――――――――――――――――――――<br><br>【Style】<br>Change Style using the Style button at the bottom of the screen.<br><br>A unit''s Style is only active when that unit is taking an action. Style use is disabled when unit is deployed using Pair Up or when unit is equipped with multiple skills that have a Style.','Dragons Ire 3',null,false,400,'Infantry,  Armored,  Cavalry,  Flying','Red Breath,  Blue Breath,  Green Breath,  Colorless Breath',null,'0,0,0,0,0',null,null,'random_owner'),
  ('DR Tenet Imbue','D/R Tenet Imbue','D/R Tenet Imbue','SID_守魔信念・治癒','passivec',null,null,'At start of player phase or enemy phase, grants 【Bulwark】to unit for 1 turn, and grants Def/Res+6 and【Imbue】to unit and allies within 2 spaces of unit for 1 turn.<br><br>Grants bonus to unit''s Def/Res = number of allies within 3 rows or 3 columns centered on unit × 2 (max 6), unit deals +5 damage (excluding area-of-effect Specials), and reduces damage from foe''s first attack by 5 during combat ("first attack" normally means only the first strike; for effects that grant "unit attacks twice," it means the first and second strikes).<br><br>【Bulwark】<br>Foes with Range = 1 cannot move through spaces adjacent to unit (does not affect foes with Pass skills). Foes with Range = 2 cannot move through spaces within 2 spaces of unit (does not affect foes with Pass skills).<br><br>【Imbue】<br>Reduces the effect of【Deep Wounds】on unit by 50% during combat, and restores 40% of unit''s maximum HP as unit''s combat begins for 1 turn (triggers after effects that deal damage as combat begins; only highest value applied; does not stack).<br><br>【Deep Wounds】<br>Unit''s HP cannot be healed through its next action.','DefRes Oath 3',null,false,300,'Infantry','Red Sword,  Blue Lance,  Green Axe,  Red Breath,  Blue Breath,  Green Breath,  Colorless Breath,  Red Beast,  Blue Beast,  Green Beast,  Colorless Beast',null,'0,0,0,0,0',null,null,'random_owner'),
  ('Rite of Rising','Rite of Rising','Rite of Rising','SID_宝杯の儀','special',null,null,'When Special triggers, boosts damage by unit''s Def.<br><br>For unit and allies within 3 rows or 3 columns centered on unit, grants Atk/Spd/Def/Res+5 and unit and allies can counterattack regardless of foe''s range during combat.<br><br>Reduces damage from foe''s attacks by 40% (excluding area-of-effect Specials) and neutralizes effects that inflict "Special cooldown charge -X" on unit during combat. If unit''s HP > 1 and foe would reduce unit''s HP to 0 during combat, unit survives with 1 HP (once per combat; does not stack with other similar effects; when this effect triggers, other similar effects granted to unit are considered triggered and vice-versa).<br><br>For certain target allies, if foe initiates combat, and if ally''s HP > 1 and foe would reduce ally''s HP to 0 during combat, ally survives with 1 HP, and after combat, restores 99 HP to ally (if support partner is on player team, targets any support partner; otherwise, targets ally with the highest Res at start of battle, excluding unit; "at start of battle" excludes increases to Res granted after ally is deployed, such as Legendary Effects, Mythic Effects, Bonus Heroes, Great Talent, etc.; effect only triggers for player''s team once per map; does not stack with other similar effects; when this effect triggers, other similar effects granted to allies are considered triggered and vice-versa).','Glacies',null,true,500,'Infantry,  Armored,  Cavalry,  Flying',null,null,null,5,null,'offensive_special,random_owner'),
  ('Solitary Breath','Solitary Breath','Solitary Breath','SID_隠棲のブレス','weapon',1,null,'Accelerates Special trigger (cooldown count-1). If foe''s Range = 2, calculates damage using the lower of foe''s Def or Res.<br><br>At start of player phase or enemy phase, grants Atk/Spd+6,【Reflex】,【Fringe Bonus】, and "foe cannot make a follow-up attack" to unit and allies within 2 spaces of unit for 1 turn.<br><br>Grants Atk/Spd/Def/Res+15 to unit, unit deals +25 damage (excluding area-of-effect Specials), reduces damage from foe''s attacks by 15 (excluding area-of-effect Specials), reduces damage from foe''s Specials by an additional 15 (excluding area-of-effect Specials), decreases Spd difference necessary for unit to make a follow-up attack by X and increases Spd difference necessary for foe to make a follow-up attack by X (if unit''s Def is greater than foe''s Def, X = 10 + difference between Def stats × 2; otherwise, X = 10), and grants Special cooldown count-2 to unit before unit''s first follow-up attack during combat.<br><br>【Reflex】<br>Reduces damage from foe''s first attack by 7 during combat ("first attack" normally means only the first strike; for effects that grant "unit attacks twice," it means the first and second strikes) and unit''s next attack deals damage = total damage reduced from foe''s first attack (by any source, including other skills; resets at end of combat). (For 1 turn.)<br><br>【Fringe Bonus】<br>Grants bonus to Atk/Spd/Def/Res during combat = highest bonus on each stat between unit and allies within 2 spaces of unit for 1 turn. Calculates each stat bonus independently.','Flametongue',null,true,400,'Infantry,  Armored,  Cavalry,  Flying','Red Breath,  Blue Breath,  Green Breath,  Colorless Breath',16,'0,16,0,0,0',-1,null,'random_owner')
on conflict (wiki_name) do nothing;

-- 2) Learnset lié (hero_id direct)
insert into feh.hero_learnset (hero_id, unit_wiki_name, skill_name, unlock_rarity) values
  ('rhea-the-final-child-1410','Rhea The Final Child','Fire Breath',1),
  ('rhea-the-final-child-1410','Rhea The Final Child','AtkRes Scowl 1',2),
  ('rhea-the-final-child-1410','Rhea The Final Child','DefRes Oath 1',2),
  ('rhea-the-final-child-1410','Rhea The Final Child','Dragons Ire 1',2),
  ('rhea-the-final-child-1410','Rhea The Final Child','Fire Breath Plus',2),
  ('rhea-the-final-child-1410','Rhea The Final Child','AtkRes Scowl 2',3),
  ('rhea-the-final-child-1410','Rhea The Final Child','Chilling Wind',3),
  ('rhea-the-final-child-1410','Rhea The Final Child','DefRes Oath 2',3),
  ('rhea-the-final-child-1410','Rhea The Final Child','Dragons Ire 2',3),
  ('rhea-the-final-child-1410','Rhea The Final Child','Flametongue',3),
  ('rhea-the-final-child-1410','Rhea The Final Child','AtkRes Scowl 3',4),
  ('rhea-the-final-child-1410','Rhea The Final Child','DefRes Oath 3',4),
  ('rhea-the-final-child-1410','Rhea The Final Child','Dragons Ire 3',4),
  ('rhea-the-final-child-1410','Rhea The Final Child','Glacies',4),
  ('rhea-the-final-child-1410','Rhea The Final Child','ADR Slam',5),
  ('rhea-the-final-child-1410','Rhea The Final Child','Distant Breath',5),
  ('rhea-the-final-child-1410','Rhea The Final Child','DR Tenet Imbue',5),
  ('rhea-the-final-child-1410','Rhea The Final Child','Rite of Rising',5),
  ('rhea-the-final-child-1410','Rhea The Final Child','Solitary Breath',5);

commit;
